var appCL =
  'If you find a bug, or have a suggestion, please let me know at '
+ '<a class=ubLink href="https://github.com/StewVed/memguess/issues" target=_blank>GitHub Issues</a>'
+ '<hr>'
+ '<p class="B C">27th May 2017</p> '
+ '<ul><li>' + zImp + 'Moved the level indicator to the center of the game.'
+ '</li><li>' + zBug + 'The above improvement, and a couple other tweaks fixed the bug where the game didn&apos;t render correctly when in landscape (longer width than height).'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">15th April 2017</p> '
+ '<ul><li>' + zBug + 'Added new game on closing settings.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">2nd April 2017</p> '
+ '<ul><li>' + zDev + 'Adapted the project to use my Global general files.'
+ '</li></ul>'
+ '<hr>'
+ 'Earlier delevopment can be found on <a class=ubLink href="https://github.com/StewVed/memguess/commits/master" target=_blank>GitHub Commits</a>'
;
