var appCL =
  'If you find a bug, or have a suggestion, please let me know at '
+ '<a class=ubLink href="https://github.com/StewVed/memguess/issues" target=_blank>GitHub Issues</a>'
+ '<hr>'
+ '<p class="B C">18th July 2020</p> '
+ '<ul><li>' + zImp + 'tweaked button animation'
+ '</li><li>' + zImp + 'tweaked game icon (svg)'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">12th July 2020</p> '
+ '<ul><li>' + zImp + 'Tweaked position of the buttons to be more central.'
+ '</li><li>' + zImp + 'Added <q>springy</q> animation to buttons.'
+ '</li><li>' + zImp + 'Made the memory mode start on level 3 instead of 1.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">2nd December 2019</p> '
+ '<ul><li>' + zBug + 'The amount of turns user has played should now work in Settings.'
+ '</li><li>' + zImp + 'The memory/guess chooser button was tweaked.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">10th September 2019</p> '
+ '<ul><li>' + zImp + 'removed zappversion - not used now.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">18h April 2019</p> '
+ '<ul><li>' + zBug + 'Small fix for the font size in landscape mode.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">27th May 2017</p> '
+ '<ul><li>' + zImp + 'Moved the level indicator to the center of the game.'
+ '</li><li>' + zBug + 'The above improvement, and a couple other tweaks fixed the bug where the game didn&apos;t render correctly when in landscape (longer width than height).'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">15th April 2017</p> '
+ '<ul><li>' + zBug + 'Added new game on closing settings.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">2nd April 2017</p> '
+ '<ul><li>' + zDev + 'Adapted the project to use my Global general files.'
+ '</li></ul>'
+ '<hr>'
+ 'Earlier delevopment can be found on <a class=ubLink href="https://github.com/StewVed/memguess/commits/master" target=_blank>GitHub Commits</a>'
;
